@startuml CalendarApp ER Diagram

entity "Events" {
  *EventID : int <<generated>> [PK]
  StartTime : time [R]
  EndTime : time [R]
  StartDate : date [R]
  EndDate : date 
  Frequency : int [R]
  Interval : int <<default 0>>
  {field}Title : varchar(255) [R]
  Description : text
  Location : text
}

entity "EventInstance" {
  *EventInstanceID : int <<generated>> [PK]
  *EventID : int [FK]
  StartDateTime : timestamp [R]
  EndDateTime : timestamp [R]
}

Events ||..o{ EventInstance 

note right of Events
Events contain rules that are used to create EventInstances.
Frequency determines basic recurrence rules. It can be:
0: not repeating
1: every day
2: every week
3: every month
4: every year
5: Xth week of every month
6: Xth day of Xth month every year
7: Xth week of Xth month every year

Interval determines detailed recurrence rules. Its rulesets change depending on the frequency:
0: not applicable
Every week: 1~7 for weekdays
Every month: 1~31 for day of the month
Every year: 1~356 for day in the year
Xth week of every month: 2 digits, where the first digit is the week number (1-5) and the second
digit is the weekday (1=Monday, ... 7=Sunday)
    For example: 23 means the 2nd Wednesday of the month
Xth day of Xth month every year: 4 digits, where the first two digits are the month (01-12) and
the last two digits are the day (01-31)
    For example: 0307 means March 7th
Xth week of Xth month every year: 4 digits, where the first two digits are the month (01-12), the
third digit is the week of the month (1-5), and the last digit is the weekday (1=Monday, ... 7=Sunday)
    For example: 0823 means the 3rd Friday of August
end note

@enduml